kur/WebUI/Controllers/CategoriesController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Interfaces.Entities;
using Interfaces.Interfaces;

namespace WebUI.Controllers
{
  public class CategoriesController : Controller
  {
    private readonly ICategoriesRepository _repository;

    public CategoriesController(ICategoriesRepository repository)
    {
      _repository = repository;
    }

    // GET: Categories
    public ActionResult Index()
    {
      var categories = new List<Category>();
      categories.AddRange(_repository.GetAllCategories());

      return View(categories);
    }

    public ActionResult CreateCategory()
    {
      return View();
    }

    [HttpPost]
    public ActionResult CreateCategory(Category category)
    {
      if (category != null)
      {
        _repository.Create(category); 
      }

      return RedirectToAction("Index");
    }
  }
}

kur/WebUI/Controllers/HomeController.cs
using System.Web.Mvc;

namespace WebUI.Controllers
{
  public class HomeController : Controller
  {
    public ActionResult Index()
    {
      return View();
    }

    public ActionResult About()
    {
      return View();
    }

    public ActionResult Contact()
    {
      return View();
    }
  }
}

kur/WebUI/Controllers/ProductsController.cs
using System.Web.Mvc;
using Interfaces.Entities;
using Interfaces.Interfaces;

namespace WebUI.Controllers
{
  public class ProductsController : Controller
  {
    private readonly IProductRepository _repo;

    private readonly ITypesRepository _typesRepository;

    public ProductsController(
      IProductRepository repo,
      ITypesRepository typesRepository)
    {
      _repo = repo;
      _typesRepository = typesRepository;
    }

    public ActionResult Index(int? typeId, string typeName)
    {
      if (typeId.HasValue)
      {
        var products = _repo.GetProductsByType(typeId.Value);
        ViewBag.Type = typeName;
        return View(products);
      }

      return new EmptyResult();
    }

    public ActionResult AddProduct(int typeId)
    {
      var newProd = new ProductCreate
      {
        Manufacturers = new SelectList(_repo.GetManuf(), "Key", "Value"),
        Deliveries = new SelectList(_repo.GetDeliveries(), "Key", "Value")
      };
      if (typeId != 0)
      {
        newProd.ProductType = _typesRepository.GetProductTypeCreateById(typeId);
        foreach (var item in newProd.ProductType.AttributeDescriptions)
        {
          newProd.Attributes.Add(string.Empty);
        }
      }

      return View(newProd);
    }

    [HttpPost]
    public ActionResult AddProduct(ProductCreate newProduct)
    {
      newProduct.Manufacturers = new SelectList(_repo.GetManuf(), "Key", "Value");
      newProduct.Deliveries = new SelectList(_repo.GetDeliveries(), "Key", "Value");
      if (newProduct.TypeId != 0)
      {
        newProduct.ProductType = _typesRepository.GetProductTypeCreateById(newProduct.TypeId);
      }
      if (ModelState.IsValid)
      {
        _repo.Create(newProduct);

        return RedirectToAction("Index", new { typeId = newProduct.TypeId });
      }

      return View(newProduct);
    }

    public ActionResult Details(int id)
    {
      return View(_repo.GetById(id));
    }
  }
}

kur/WebUI/Controllers/TypesController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Interfaces.Entities;
using Interfaces.Interfaces;

namespace WebUI.Controllers
{
  public class TypesController : Controller
  {
    private readonly ITypesRepository _repository;

    public TypesController(ITypesRepository repository)
    {
      _repository = repository;
    }

    public TypesController()
    {

    }

    // GET: Types
    public ActionResult Index(int? categoryId)
    {
      if (categoryId.HasValue)
      {
        var types = new List<ProductType>();
        types.AddRange(_repository.GetTypesByCategory(categoryId.Value));

        return View(types);
      }

      return new EmptyResult();
    }

    public ActionResult CreateType(int categoryId)
    {
      var newType = new ProductTypeCreate
      {
        AttributeDescriptions = new List<ProductTypeField>(),
        CategoryId = categoryId
      };

      newType.AttributeDescriptions.Add(new ProductTypeField { AttributeName = string.Empty });
      newType.AttributeDescriptions.Add(new ProductTypeField { AttributeName = string.Empty });
      newType.AttributeDescriptions.Add(new ProductTypeField { AttributeName = string.Empty });
      newType.AttributeDescriptions.Add(new ProductTypeField { AttributeName = string.Empty });
      newType.AttributeDescriptions.Add(new ProductTypeField { AttributeName = string.Empty });

      return View(newType);
    }

    [HttpPost]
    public ActionResult CreateType(ProductTypeCreate newType)
    {
      if (ModelState.IsValid)
      {
        _repository.Create(newType);

        return RedirectToAction("Index", new { categoryId = newType.CategoryId });
      }

      return View(newType);
    }
  }
}

kur/WebUI/Views/Categories/CreateCategory.cshtml
@model Interfaces.Entities.Category

@{
    ViewBag.Title = "CreateCategory";
}

<h2>CreateCategory</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

kur/WebUI/Views/Categories/Index.cshtml
@model IEnumerable<Interfaces.Entities.Category>

@{
  ViewBag.Title = "Categories";
}

<h2>Categories</h2>

<p>
  @Html.ActionLink("Create New", "CreateCategory")
</p>
<table class="table">
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.Name)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Image)
    </th>
    <th></th>
  </tr>

  @foreach (var item in Model)
  {
    <tr>
      <td>
        @Html.ActionLink(item.Name, "Index", "Types", new { categoryId = item.Id }, null)
      </td>
        <td>
            <img src="~/@Url.Content(item.Image)" alt="Image not provided" width="50" height="50"/>
        </td>
      <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) 
      </td>
    </tr>
  }

</table>

kur/WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h1>Welcome my dear</h1>

kur/WebUI/Views/Products/AddProduct.cshtml
@model Interfaces.Entities.ProductCreate

@{
  ViewBag.Title = "AddProduct";
}

<h2>Add new product</h2>

@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
      @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.Label("Manufacturer", htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownListFor(model => model.ManufacturerId, Model.Manufacturers)
        @Html.ValidationMessageFor(model => model.ManufacturerId, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Warranty, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Warranty, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Warranty, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
      </div>
    </div>
    
    <div class="form-group">
      @Html.Label("Delivery", htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownListFor(model => model.DeliveryId, Model.Deliveries)
      </div>
    </div>

      <div class="form-group">
      @Html.LabelFor(model => model.StorageSerial, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.StorageSerial, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.StorageSerial, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      <h2>Attributes</h2>

      @for (int i = 0; i < Model.Attributes.Count; i++)
      {
        <div class="col-md-10">
          @Html.Label(Model.ProductType.AttributeDescriptions[i].AttributeName, htmlAttributes: new { @class = "control-label col-md-2" })
          @Html.TextBoxFor(create => create.Attributes[i], new { @class = "text-danger" })
        </div>
      }
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Create" class="btn btn-default" />
      </div>
    </div>
  </div>
}

<div>
  @Html.ActionLink("Back to List", "Index", new { typeId = Request.QueryString["typeId"] })
</div>

kur/WebUI/Views/Products/Buy.cshtml
@model Interfaces.Entities.UserBuying

@{
    ViewBag.Title = "Buy";
}

<h2>Buy</h2>

@using (Html.BeginForm())
{
  @Html.
}   

kur/WebUI/Views/Products/Details.cshtml
@model Interfaces.Entities.Product

@{
  ViewBag.Title = "Details";
}


<div>
  <h1>
    @Html.DisplayFor(model => model.Name)
  </h1>

  <div style="display: -webkit-inline-box;">
    <dl class="dl-horizontal">  
      <dt>
        @Html.DisplayNameFor(model => model.Manufacturer)
      </dt>

      <dd>
        @Html.DisplayFor(model => model.Manufacturer)
      </dd>

      <dt>

      </dt>

      <dd>
        @Html.DisplayFor(model => model.ManufacturerInfo)
      </dd>

      <dt>
        @Html.DisplayNameFor(model => model.Price)
      </dt>

      <dd>
        @Html.DisplayFor(model => model.Price)
      </dd>

      <dt>
        @Html.DisplayNameFor(model => model.Warranty)
      </dt>

      <dd>
        @Html.DisplayFor(model => model.Warranty)
      </dd>

      <dt>
        @Html.DisplayNameFor(model => model.Delivery)
      </dt>

      <dd>
        @Html.DisplayFor(model => model.Delivery)
      </dd>

      <dt>
      </dt>

      <dt>
        @Html.DisplayNameFor(model => model.Count)
      </dt>

      <dd>
        @Html.DisplayFor(model => model.Count)
      </dd>

      <dt>
        @Html.DisplayNameFor(model => model.StorageSerial)
      </dt>

      <dd>
        @Html.DisplayFor(model => model.StorageSerial)
      </dd>

    </dl>
  </div>
  <div style="display: -webkit-inline-box; margin-left: 110px">
    <img src="~/@Url.Content(Model.Picture)" alt="Image not provided" width="500" height="500" />
    <div>
      @foreach (var atr in Model.Attributes)
      {
        <ul>
          <li>@Html.Label(atr)</li>
        </ul>
      }
    </div>
  </div>

</div>

<p>
  @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
  @Html.ActionLink("Back to List", "Index")
</p>

kur/WebUI/Views/Products/Index.cshtml
@model IEnumerable<Interfaces.Entities.Product>

@{
  ViewBag.Title = "Products of " + ViewBag.Type;
}

<h2>Products of @ViewBag.Type</h2>

<p>
  @Html.ActionLink("Create New", "AddProduct", new { typeId = Request.QueryString["typeId"]})
</p>
<table class="table">
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.Name)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Manufacturer)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.ManufacturerInfo)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Price)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Warranty)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Delivery)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Picture)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.Count)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.StorageSerial)
    </th>
    <th></th>
  </tr>

  @foreach (var item in Model)
  {
    <tr>
      <td>
        @Html.DisplayFor(modelItem => item.Name)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Manufacturer)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.ManufacturerInfo)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Price)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Warranty)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Delivery)
      </td>
      <td>
        <img src="~/@Url.Content(item.Picture)" alt="Image not provided" width="50" height="50" />
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Count)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.StorageSerial)
      </td>
      <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
      </td>
    </tr>
  }

</table>

kur/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@ViewBag.Title</title>
  @Styles.Render("~/Content/css")
  @Scripts.Render("~/bundles/modernizr")
  @Scripts.Render("~/bundles/jqueryval")

</head>
<body>
  <div class="jumbotron nav">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="nav">
        <ul class="navbar-nav">
          @Html.ActionLink("Mega store home page", "Index", "Home", new { area = "" }, null)
        </ul>
        <ul class="navbar-nav">
          @Html.ActionLink("Product categories", "Index", "Categories")
        </ul>
      </div>
    </div>

  </div>
  <div class="jumbotron table">
    @RenderBody()
    <hr />
    <footer>
      <p>&copy; @DateTime.Now - (c) A.Bulac & Bubee incorporated</p>
    </footer>
  </div>

  @Scripts.Render("~/bundles/jquery")
  @Scripts.Render("~/bundles/bootstrap")
  @RenderSection("scripts", required: false)
</body>
</html>

kur/WebUI/Views/Types/CreateType.cshtml
@model Interfaces.Entities.ProductTypeCreate

@{
  ViewBag.Title = "CreateType";
}

<h2>CreateType</h2>

@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <h4>ProductTypeCreate</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
      @Html.LabelFor(model => model.TypeName, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.TypeName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.TypeName, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      <h2>Attributes</h2>
      @for (int i = 0; i < Model.AttributeDescriptions.Count; i++)
      {
        <div class="col-md-10">
          @Html.TextBoxFor(create => create.AttributeDescriptions[i].AttributeName, new { @class = "text-danger" })
          @Html.DropDownListFor(create => create.AttributeDescriptions[i].AttributeType, new SelectList(Model.AttributeDescriptions.First().TypesList, "Key", "Value"))
        </div>
      }
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Create" class="btn btn-default" />
      </div>
    </div>
  </div>
}

<div>
  @Html.ActionLink("Back to List", "Index")
</div>

kur/WebUI/Views/Types/Index.cshtml
@model IEnumerable<Interfaces.Entities.ProductType>

@{
  ViewBag.Title = "Types of ";
}

<h2>Product Types</h2>

<p>
  @Html.ActionLink("Create New", "CreateType", new { categoryId = Request.QueryString["categoryId"] })
</p>
<table class="table">
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.Name)
    </th>
    <th>
      Products
    </th>
  </tr>

  @foreach (var item in Model)
  {
    <tr>
      <td>
        @Html.ActionLink(item.Name, "Index", "Products", new { typeId = item.Id, typeName = item.Name }, null)
      </td>
      <td></td>
      <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) 
      </td>
    </tr>
  }

</table>